# Generated by Django 6.0.3 on 2026-04-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Blend', 'Blend'), ('Pure Arabica', 'Pure Arabica'), ('Green Coffee', 'Green Coffee')], max_length=100),
        ),
    ]
